"""Report generation module.

Version: 0.3.0
Path: src/report.py
"""

from pathlib import Path
from typing import Dict, Any
import csv


def generate_reports(summary: str, analysis: Dict[str, Any], output_dir: Path) -> None:
    """Create HTML and CSV reports from analysis and summary.

    Parameters
    ----------
    summary:
        Text generated by the LLM summarizing the analysis.
    analysis:
        Dictionary with analysis metrics.
    output_dir:
        Directory where reports will be written.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "report.html").write_text(
        f"<html><body><pre>{summary}</pre></body></html>"
    )
    with open(output_dir / "report.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["metric", "value"])
        for key, value in analysis.items():
            writer.writerow([key, value])
